import { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: "United States", code: "us", language: "English", difficulty: 'easy' },
  { name: "United Kingdom", code: "gb", language: "English", difficulty: 'easy' },
  { name: "France", code: "fr", language: "French", difficulty: 'easy' },
  { name: "Germany", code: "de", language: "German", difficulty: 'easy' },
  { name: "Spain", code: "es", language: "Spanish", difficulty: 'easy' },
  { name: "Italy", code: "it", language: "Italian", difficulty: 'easy' },
  { name: "Japan", code: "jp", language: "Japanese", difficulty: 'easy' },
  { name: "China", code: "cn", language: "Chinese", difficulty: 'easy' },
  { name: "Canada", code: "ca", language: "English", difficulty: 'medium' },
  { name: "Australia", code: "au", language: "English", difficulty: 'medium' },
  { name: "Mexico", code: "mx", language: "Spanish", difficulty: 'medium' },
  { name: "Argentina", code: "ar", language: "Spanish", difficulty: 'medium' },
  { name: "Brazil", code: "br", language: "Portuguese", difficulty: 'medium' },
  { name: "Portugal", code: "pt", language: "Portuguese", difficulty: 'medium' },
  { name: "India", code: "in", language: "Hindi", difficulty: 'medium' },
  { name: "Russia", code: "ru", language: "Russian", difficulty: 'medium' },
  { name: "South Korea", code: "kr", language: "Korean", difficulty: 'medium' },
  { name: "Egypt", code: "eg", language: "Arabic", difficulty: 'medium' },
  { name: "Saudi Arabia", code: "sa", language: "Arabic", difficulty: 'medium' },
  { name: "Nigeria", code: "ng", language: "English", difficulty: 'medium' },
  { name: "South Africa", code: "za", language: "English", difficulty: 'medium' },
  { name: "Turkey", code: "tr", language: "Turkish", difficulty: 'medium' },
  { name: "Netherlands", code: "nl", language: "Dutch", difficulty: 'medium' },
  { name: "Sweden", code: "se", language: "Swedish", difficulty: 'medium' },
  { name: "Norway", code: "no", language: "Norwegian", difficulty: 'medium' },
  { name: "Finland", code: "fi", language: "Finnish", difficulty: 'medium' },
  { name: "Poland", code: "pl", language: "Polish", difficulty: 'medium' },
  { name: "Greece", code: "gr", language: "Greek", difficulty: 'medium' },
  { name: "Thailand", code: "th", language: "Thai", difficulty: 'medium' },
  { name: "Vietnam", code: "vn", language: "Vietnamese", difficulty: 'medium' },
  { name: "Indonesia", code: "id", language: "Indonesian", difficulty: 'medium' },
  { name: "Israel", code: "il", language: "Hebrew", difficulty: 'medium' },
  { name: "Switzerland", code: "ch", language: "German", difficulty: 'medium' },
  { name: "Austria", code: "at", language: "German", difficulty: 'medium' },
  { name: "Belgium", code: "be", language: "Dutch", difficulty: 'medium' },
  { name: "Ireland", code: "ie", language: "English", difficulty: 'medium' },
  { name: "New Zealand", code: "nz", language: "English", difficulty: 'medium' },
  { name: "Chile", code: "cl", language: "Spanish", difficulty: 'medium' },
  { name: "Colombia", code: "co", language: "Spanish", difficulty: 'medium' },
  { name: "Peru", code: "pe", language: "Spanish", difficulty: 'medium' },
  { name: "Ukraine", code: "ua", language: "Ukrainian", difficulty: 'medium' },
  { name: "Iran", code: "ir", language: "Persian", difficulty: 'medium' },
  { name: "Pakistan", code: "pk", language: "Urdu", difficulty: 'medium' },
  { name: "Bangladesh", code: "bd", language: "Bengali", difficulty: 'medium' },
  { name: "Philippines", code: "ph", language: "Filipino", difficulty: 'medium' },
  { name: "Malaysia", code: "my", language: "Malay", difficulty: 'medium' },
  { name: "Czech Republic", code: "cz", language: "Czech", difficulty: 'medium' },
  { name: "Hungary", code: "hu", language: "Hungarian", difficulty: 'medium' },
  { name: "Romania", code: "ro", language: "Romanian", difficulty: 'medium' },
  { name: "Denmark", code: "dk", language: "Danish", difficulty: 'medium' },
  { name: "Ethiopia", code: "et", language: "Amharic", difficulty: 'hard' },
  { name: "Mongolia", code: "mn", language: "Mongolian", difficulty: 'hard' },
  { name: "Cambodia", code: "kh", language: "Khmer", difficulty: 'hard' },
  { name: "Nepal", code: "np", language: "Nepali", difficulty: 'hard' },
  { name: "Sri Lanka", code: "lk", language: "Sinhala", difficulty: 'hard' },
  { name: "Estonia", code: "ee", language: "Estonian", difficulty: 'hard' },
  { name: "Latvia", code: "lv", language: "Latvian", difficulty: 'hard' },
  { name: "Lithuania", code: "lt", language: "Lithuanian", difficulty: 'hard' },
  { name: "Georgia", code: "ge", language: "Georgian", difficulty: 'hard' },
  { name: "Armenia", code: "am", language: "Armenian", difficulty: 'hard' },
  { name: "Iceland", code: "is", language: "Icelandic", difficulty: 'hard' },
  { name: "Albania", code: "al", language: "Albanian", difficulty: 'hard' },
  { name: "Slovenia", code: "si", language: "Slovenian", difficulty: 'hard' },
  { name: "Croatia", code: "hr", language: "Croatian", difficulty: 'hard' },
  { name: "Serbia", code: "rs", language: "Serbian", difficulty: 'hard' },
];